// @flow

const FETCH_PEOPLE_START:string = 'FETCH_PEOPLE_START';
const FETCH_PEOPLE_SUCCESS:string = 'FETCH_PEOPLE_SUCCESS';
const FETCH_PEOPLE_ERROR:string = 'FETCH_PEOPLE_ERROR';

const LOGIN_SUCCESS:string = 'LOGIN_SUCCESS';
const LOGIN_FAILURE:string = 'LOGIN_FAILURE';
const LOGIN_RESET:string = 'LOGIN_RESET';
const LOGIN_LOGOUT:string = 'LOGIN_LOGOUT';

export {FETCH_PEOPLE_START, FETCH_PEOPLE_SUCCESS, FETCH_PEOPLE_ERROR, LOGIN_SUCCESS, LOGIN_FAILURE, LOGIN_RESET, LOGIN_LOGOUT}