// @flow

const FETCH_PEOPLE_START: string = 'FETCH_PEOPLE_START';
const FETCH_PEOPLE_SUCCESS: string = 'FETCH_PEOPLE_SUCCESS';
const FETCH_PEOPLE_ERROR: string = 'FETCH_PEOPLE_ERROR';

const LOGIN_SUCCESS: string = 'LOGIN_SUCCESS';
const LOGIN_FAILURE: string = 'LOGIN_FAILURE';
const LOGIN_RESET: string = 'LOGIN_RESET';
const LOGIN_LOGOUT: string = 'LOGIN_LOGOUT';

const CREATE_ERROR_POPUP_SHOW: string = 'CREATE_ERROR_POPUP_SHOW';
const CREATE_ERROR_POPUP_HIDE: string = 'CREATE_ERROR_POPUP_HIDE';

const CREATE_SUCCESS_POPUP_SHOW: string = 'CREATE_SUCCESS_POPUP_SHOW';
const CREATE_SUCCESS_POPUP_HIDE: string = 'CREATE_SUCCESS_POPUP_HIDE';

export {
    FETCH_PEOPLE_START,
    FETCH_PEOPLE_SUCCESS,
    FETCH_PEOPLE_ERROR,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGIN_RESET,
    LOGIN_LOGOUT,
    CREATE_ERROR_POPUP_SHOW,
    CREATE_ERROR_POPUP_HIDE,
    CREATE_SUCCESS_POPUP_SHOW,
    CREATE_SUCCESS_POPUP_HIDE
}